import type { Metadata } from "next";

import MainHeader from "@/components/main-header/main-header";

import { nunito, sansation } from '@/lib/fonts';

import "./globals.css";

export const metadata: Metadata = {
  title: "Next MoviePedia App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${sansation.variable}`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}